language: ruby
rvm:
  - "2.1.2"
before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - cp config/config.example.yml config/config.yml
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
